# Generated by Django 5.0.3 on 2024-04-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examhalling_subject_row_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='row',
        ),
        migrations.DeleteModel(
            name='ExamHalling',
        ),
        migrations.RemoveField(
            model_name='row',
            name='exam_hall',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
