# Generated by Django 5.0.3 on 2024-04-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='column',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='row',
        ),
    ]
