# Generated by Django 5.0.3 on 2024-04-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examhall',
            name='total_columns',
        ),
        migrations.RemoveField(
            model_name='examhall',
            name='total_rows',
        ),
        migrations.AddField(
            model_name='data',
            name='exam_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examhall'),
        ),
    ]
