# Generated by Django 5.0.3 on 2024-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_examhall_total_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
