# Generated by Django 5.0.3 on 2024-04-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_data_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='exam_hall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examhall'),
        ),
    ]
