# Generated by Django 5.0.3 on 2024-04-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_data_exam_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='data',
            name='exam_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examhall'),
        ),
    ]
