# Generated by Django 5.0.3 on 2024-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_data_roll_number_alter_data_exam_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
