# Generated by Django 5.0.3 on 2024-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_data_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
