# Generated by Django 5.0.3 on 2024-04-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_student_student_class_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
