# Generated by Django 5.0.3 on 2024-04-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_data_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='students',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='seatingarrangement',
            name='student',
        ),
    ]
