# Generated by Django 5.0.3 on 2024-04-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_rename_students_data_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GereratingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.data')),
            ],
        ),
    ]
