# Generated by Django 5.0.3 on 2024-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_gereratingexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gereratingexam',
            name='hall',
        ),
        migrations.AddField(
            model_name='gereratingexam',
            name='hall',
            field=models.ManyToManyField(to='exam.data'),
        ),
    ]
