# Generated by Django 5.0.3 on 2024-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_gereratingexam_hall_gereratingexam_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='gereratingexam',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
