# Generated by Django 5.0.3 on 2024-04-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_gereratingexam_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gereratingexam',
            name='created_at',
        ),
    ]
