# Generated by Django 5.0.3 on 2024-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_gereratingexam_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gereratingexam',
            name='modified_at',
            field=models.CharField(max_length=50),
        ),
    ]
