# Generated by Django 5.0.3 on 2024-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_alter_gereratingexam_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gereratingexam',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
