# Generated by Django 5.0.3 on 2024-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_alter_gereratingexam_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gereratingexam',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='gereratingexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
