# Generated by Django 5.0.3 on 2024-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='gereratingexam',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6')], max_length=1, null=True),
        ),
    ]
