# Generated by Django 5.0.3 on 2024-04-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_gereratingexam_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='seatingarrangement',
            name='exam_hall',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='SeatingArrangement',
        ),
    ]
